/*
Made by: Mathew Dusome
April 2 2026 
Turso (libSQL) database module for Rust

April 2: Dray52 Added fetch by id with examples
================================
INITIAL SETUP:
================================
1. Add to mod.rs: pub mod database;
2. Sign up: https://turso.tech
3. Create DB: turso db create my-db
4. Get URL: turso db show my-db
5. Get token: turso db tokens create my-db
6. Update TURSO_URL and TURSO_AUTH_TOKEN below

7. Add dependencies to Cargo.toml. Add these 2 lines to [dependencies]:

   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"

   Then add these 2 new sections:

   [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
   ureq = { version = "2.9", features = ["json"] }
   
8. Add use statement:
    use crate::modules::database::{create_database_client, DatabaseTable};
9. Add to mod.rs:
    pub mod database;
10. To build for web: Use "Build: Web Output(Advanced)" option in the Dusome's extension.
   This will compile to WebAssembly with the wasm32 dependencies above.

================================
CUSTOMIZE YOUR DATABASE SCHEMA:
================================
1. Modify the DatabaseTable struct below
   - Add/remove fields to match your table columns
   - Use appropriate Rust types: i32 for INTEGER, String for TEXT, bool for BOOLEAN, f64 for REAL
   - Keep id: i32 (0 for INSERT means auto-generate, populated with actual ID for SELECT)
   - Use serde attributes for custom naming if needed

2. Create your table in Turso (via CLI or SQL):
   
   Using Turso CLI:
     turso db shell my-db
     CREATE TABLE my_table (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       column1 TEXT NOT NULL,
       column2 INTEGER,
       ...
     );

 
3. Column type mapping:
   - INTEGER → i32, i64
   - TEXT → String
   - REAL → f64
   - BOOLEAN → bool
   - NUMERIC → f64 or String

================================
USAGE EXAMPLES:
================================

// NOTE: The table used in these examples is called 'messages'.
    let client = create_database_client();


    // Fetch all records (for display)
    let mut records: Vec<DatabaseTable> = Vec::new();
    let fetched_results = client.fetch_table("messages").await;
    if let Ok(result) = fetched_results {
        records = result;
       // To update a ListView with these records:
        // update_listview(&mut list_view, &records);
        }
        // deleted_count is the number of records deleted
    } else {
        // Handle error
    }

    // Custom SQL queries
    if let Ok(_) = client.execute_sql("SELECT * FROM messages WHERE id > 5").await {
        // Query executed
    } else {
        // Handle error
    }

  // ---
    // Displaying records in a ListView:
    //Where 'list_view' is your ListView instance and 'records' is the Vec<DatabaseTable> fetched from the database.
    //Change the items.push! line to customize how each record is displayed in the list.
   
   fn update_listview(list_view: &mut ListView, messages: &Vec<DatabaseTable>) {
    list_view.clear();
    let mut items: Vec<String> = Vec::new();
    for (i, msg) in messages.iter().enumerate() {
        items.push(format!("  {}: ID={}, Text={}", i + 1, msg.id, msg.text));
    }
    list_view.add_items(&items);
}
*/

use serde::{Deserialize, Serialize};
use quad_net::http_request::{RequestBuilder, Method};

// Helper function for serde to skip serializing id when it's 0
fn is_zero(num: &i32) -> bool {
    *num == 0
}
// Please replace the libsql:// from the URL with https:
// URL of your Cloudflare Worker backend
pub const WORKER_URL: &str = "https://db-worker.mathew-dusome.workers.dev";


// ============================================================================
// CUSTOMIZE THIS STRUCT FOR YOUR DATABASE SCHEMA
// ============================================================================

/// Your database record struct - used for both INSERT and SELECT operations
/// When inserting: set id to 0 (it will be auto-generated by the database)
/// When fetching: id will be populated with the actual ID
/// 
/// Modify this struct to match your table columns:
/// #[derive(Debug, Deserialize, Serialize, Clone)]
/// pub struct DatabaseTable {
///     #[serde(default, skip_serializing_if = "is_zero")]
///     pub id: i32,
///     pub email: String,
///     pub age: i32,
///     pub active: bool,
///     pub score: f64,
/// }
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct DatabaseTable {
    #[serde(default, skip_serializing_if = "is_zero")]
    pub id: i32,
    pub text: String,
    // Example: Add more fields like this:
    // pub email: String,
    // pub age: i32,
    // pub active: bool,
    // pub score: f64,
}

// ============================================================================
// CONVENIENCE FUNCTIONS
// ============================================================================

#[allow(unused)]
pub fn create_database_client() -> DatabaseClient {
    DatabaseClient::new(WORKER_URL.to_string())
}


/// Create a table with custom name and schema
/// The table name and columns are fully customizable
/// Update this function if you want to change the table structure
/// 
/// Example for different schemas:
/// ```
/// // For users table:
/// CREATE TABLE users (
///   id INTEGER PRIMARY KEY AUTOINCREMENT,
///   email TEXT NOT NULL UNIQUE,
///   age INTEGER,
///   active BOOLEAN DEFAULT 1,
///   score REAL
/// )
/// 
/// // For products table:
/// CREATE TABLE products (
///   id INTEGER PRIMARY KEY AUTOINCREMENT,
///   name TEXT NOT NULL,
///   price REAL,
///   in_stock BOOLEAN
/// )
/// ```

pub struct DatabaseClient {
    worker_url: String,
}

impl DatabaseClient {
        pub async fn insert_record<T: Serialize>(&self, table: &str, record: &T) -> Result<i64, Box<dyn std::error::Error>> {
            let payload = serde_json::json!({
                "action": "insert",
                "table": table,
                "record": record
            });
            let resp = self.send_request(&payload).await?;
            Ok(resp["id"].as_i64().unwrap_or(0))
        }

        pub async fn update_record_by_struct<T: Serialize>(&self, table: &str, record: &T) -> Result<i64, Box<dyn std::error::Error>> {
            let payload = serde_json::json!({
                "action": "update",
                "table": table,
                "record": record
            });
            let resp = self.send_request(&payload).await?;
            Ok(resp["updated"].as_i64().unwrap_or(0))
        }

        pub async fn update_record_by_id(&self, table: &str, id: i64, column: &str, value: &serde_json::Value) -> Result<i64, Box<dyn std::error::Error>> {
            let payload = serde_json::json!({
                "action": "update_by_column",
                "table": table,
                "id": id,
                "column": column,
                "value": value
            });
            let resp = self.send_request(&payload).await?;
            Ok(resp["updated"].as_i64().unwrap_or(0))
        }

        pub async fn delete_record_by_id(&self, table: &str, id: i64) -> Result<i64, Box<dyn std::error::Error>> {
            let payload = serde_json::json!({
                "action": "delete",
                "table": table,
                "id": id
            });
            let resp = self.send_request(&payload).await?;
            Ok(resp["deleted"].as_i64().unwrap_or(0))
        }

        async fn send_request(&self, payload: &serde_json::Value) -> Result<serde_json::Value, Box<dyn std::error::Error>> {
            // Use quad-net http_request for HTTP requests on all platforms
            let mut request = RequestBuilder::new(&self.worker_url)
                .method(Method::Post)
                .header("Content-Type", "application/json")
                .body(&payload.to_string())
                .send();

            // Poll the request until we get a response
            loop {
                if let Some(result) = request.try_recv() {
                    let text = result.map_err(|e| format!("HTTP error: {}", e))?;
                    let json: serde_json::Value = serde_json::from_str(&text)?;
                    return Ok(json);
                }
                macroquad::prelude::next_frame().await;
            }
        }
    pub fn new(worker_url: String) -> Self {
        Self { worker_url }
    }


   
    #[allow(unused)]
    pub async fn fetch_table<T: for<'de> Deserialize<'de>>(&self, table: &str) -> Result<Vec<T>, Box<dyn std::error::Error>> {
        let payload = serde_json::json!({
            "action": "fetch",
            "table": table
        });
        let resp = self.send_request(&payload).await?;
        let records = resp["records"].as_array().cloned().unwrap_or_default();
        let mut result = Vec::new();
        for record in records {
            result.push(serde_json::from_value(record)?);
        }
        Ok(result)
    }
    #[allow(unused)]
    pub async fn fetch_record_by_id<T: for<'de> Deserialize<'de>>(&self, table: &str, id: i64) -> Result<Option<T>, Box<dyn std::error::Error>> {
        let payload = serde_json::json!({
            "action": "fetch_by_id",
            "table": table,
            "id": id
        });
        let resp = self.send_request(&payload).await?;
        let record = resp.get("record").cloned();
        match record {
            Some(val) if !val.is_null() => Ok(Some(serde_json::from_value(val)?)),
            _ => Ok(None)
        }
    }



    // All direct SQL and WASM FFI helpers removed; only HTTP/Worker logic remains
}
